server:
  port: 7000
spring:
  h2:
    console:
      path: /console
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    
  application:
    name: media-service
    
   
